version: '3'

networks:
  Mynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.20.0.0/16"
          gateway: "10.20.0.1"

services:

  twitter:
    image: img_proy1
    ports:
      - 3322:8080
    networks:
      - Mynet

  bd_mysql:
    container_name: mysql_proy1
    image: mysql:5.7
    ports:
      - 3344:3306
    networks:
      - Mynet
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root

  redis:
    image: redis:6.2.6
    networks:
      - Mynet
    